# config.yaml
dataset:
  psych_depression_physical_symptons:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 4
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2

  psych_depression_physical_symptons_reg:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.001
    batch_size: 4
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2  

  zebra:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2
  
  zebra_special:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2

  bal:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2

  digits:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 10

  iris:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2

  wine:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 2

  breast_cancer:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 10

  califonia_housing:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1500
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    nn_cdh_enabled: False
    patience: 100
    discount: 2

  abalone:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1500
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    nn_cdh_enabled: False
    patience: 100
    discount: 2
  
  diabets:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1500
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    nn_cdh_enabled: False
    patience: 100
    discount: 2

  body_fat:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1500
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    nn_cdh_enabled: False
    patience: 100
    discount: 2

  ziweifaces:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1500
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    nn_cdh_enabled: False
    patience: 100
    discount: 2

  mnist:
    ca_weight_sharing: False
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 100

  cifar10:
    ca_weight_sharing: False
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 100

  svhn:
    ca_weight_sharing: False
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 100

  cifar100:
    ca_weight_sharing: False
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 100
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 100

  covid_anxious:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_depressed:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_lonely:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_hopeless:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_physical:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_anxious_reg:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.0001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_depressed_reg:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.0001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_lonely_reg:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 1000
    learning_rate: 0.0001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_hopeless_reg:
    ca_weight_sharing: True
    top_case_enabled: True
    training_epochs: 1000
    learning_rate: 0.01
    batch_size: 16
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  covid_physical_reg:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 2000
    learning_rate: 0.0001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 100
    discount: 40

  sst1:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 100
    learning_rate: 0.001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 7
    discount: 40

  sst2:
    ca_weight_sharing: True
    top_case_enabled: False
    training_epochs: 100
    learning_rate: 0.001
    batch_size: 32
    top_k: 5
    class_weight_sharing: True
    patience: 7
    discount: 40